site_name: p3-tee

theme:
  name: material
  #name: mkdocs
  # custom_dir: material

  # 404 page
  static_templates:
  - 404.html
    
  navigation_depth: 3
  
  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    # - navigation.instant
    # - navigation.sections
    - navigation.tabs
  palette:
    scheme: default
    primary: orange
    accent: orange
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

plugins:
  - search
#  - git-revision-date-localized

nav:
  #- quickstart: quickstart.md
  - setup(sp23): quickerstart.md
  - app samples: helloworld.md 
  - task: secure-vision.md
  - troubleshoot: issues.md  
  - /porting: porting.md  
  - /cleanup: cleanup.md  
  - /lib: sod.md
  - /wsl: wsl-ubuntu-howto.md
  
  #- Device:
   # - Hikey: devices/hikey.md
    #- Odroid: devices/odroid.md
  #- /dump: dump.md
